---
title: Mindset Dojo

google_analytics_id: G-7PD1BFF7RG

collections:
  authors:
    output: true
    permalink: /authors/:name/
  insight:
    output: true
    permalink: /insight/:slug/

action_links:
  program: /program/
  project: /project/
  connect: https://connect.mindset.dojo.center
  repo: https://github.com/mindset-dojo/mindset-dojo.github.io

header_links:
  - label: MISSION
    href: /
  - label: PROGRAM
    href: /program/
  - label: PROJECT
    href: /project/
  - label: PATTERN
    href: /pattern/
  - label: INSIGHT
    href: /insight/

footer_primary_links:
  - label: MISSION
    href: /
  - label: PROGRAM
    href: /program/
  - label: PROJECT
    href: /project/
  - label: PATTERN
    href: /pattern/
  - label: INSIGHT
    href: /insight/
  - label: CONTACT
    href: https://connect.mindset.dojo.center
    external: true

footer_secondary_links:
  - label: Privacy Policy
    href: /privacy/
  - label: Open Source License
    href: /license/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
...
