---
mantra: "Don't Hoard. Share."
context:
  core_motivations:
    - "Our project is a shared practice of simplicity and coherence."
    - "We refine our systems, language, and flow through steady, mindful iteration."
    - "Each contribution strengthens the pattern of fearlessness in form."
  contribution_motivations:
    - "Make contribution as natural as conversation."
    - "Create infrastructure that teaches as it grows."
    - "Invite courage through transparency and simplicity."
  contribution_invitations:
    - "You notice a friction in the docs."
    - "You refactor a phrase or function toward clarity."
    - "You offer a pattern that helps others move with ease."
  repo_call_to_action: Enter the Dojo
designations:
  - label: Social Cultivator
    intention: Shape resonance and visibility through mindful presence
    aspects:
      - label: Attend Cultivator Mat periodically
      - label: Share dojo stories and reflections across social spaces
      - label: Shape the tone and rhythm of communication
      - label: Green Level+, sponsored by existing Cultivator
  - label: Infrastructure Cultivator
    intention: Strengthen and simplify the systems that sustain the dojo
    aspects:
      - label: Join Cultivator Mat regularly
      - label: Contribute to expertise in a mutually aligned domain
      - label: Ensure information systems reconcile with living practice
      - label: Purple Level+, sponsored by existing Cultivator
  - label: Project Cultivator
    intention: Integrate program, community, and platform work into coherent offerings
    aspects:
      - label: Lead Cultivator Mat sessions periodically
      - label: Weave interdependencies with clarity and calm
      - label: Model integrated embodiment in collaboration
      - label: Black Level, sponsored by existing Cultivator
  - label: Organizational Cultivator
    intention: Embody integrative leadership across social, technical, and brand ecosystems
    aspects:
      - label: Lead Cultivator Mat sessions regularly
      - label: Bridge all cultivation dimensions toward shared identity and rhythm
      - label: Steward organizational narrative and brand coherence
      - label: Black Level, Zen Leadership Instructor designation
