---
mantra: "Don't Hoard. Share."
context:
  intro_lines:
    - "Our project is a shared practice of simplicity and coherence"
    - "We refine our systems, language, and flow through steady, mindful iteration"
    - "Each contribution strengthens the pattern of fearlessness in form"
  scenario_lines:
    - "You notice a friction in the docs"
    - "You refactor a phrase or function toward clarity"
    - "You offer a pattern that helps others move with ease"
  why_we_build:
    - "To make contribution as natural as conversation"
    - "To create infrastructure that teaches as it grows"
    - "To invite courage through transparency and simplicity"
project_cta: "Cross the Threshold"
principles:
  - label: "Work small and reversible"
  - label: "Name things clearly"
  - label: "Express intent through structure"
  - label: "Simplify as a sign of respect"
designations:
  - label: Social Cultivator
    intention: Shape resonance and visibility through mindful presence
    aspects:
      - label: Attend Cultivator Mat periodically
      - label: Share dojo stories and reflections across social spaces
      - label: Shape the tone and rhythm of communication
      - label: Green Level+, sponsored by existing Cultivator
  - label: Infrastructure Cultivator
    intention: Strengthen and simplify the systems that sustain the dojo
    aspects:
      - label: Join Cultivator Mat regularly
      - label: Contribute to code, automation, and governance
      - label: Ensure information systems reconcile with living practice
      - label: Purple Level+, sponsored by existing Cultivator
  - label: Project Cultivator
    intention: Integrate program, community, and platform work into coherent offerings
    aspects:
      - label: Lead Cultivator Mat sessions periodically
      - label: Weave interdependencies with clarity and calm
      - label: Model integrated embodiment in collaboration
      - label: Black Level, sponsored by existing Cultivator
  - label: Organizational Cultivator
    intention: Embody integrative leadership across social, technical, and brand ecosystems
    aspects:
      - label: Lead Cultivator Mat sessions regularly
      - label: Bridge all cultivation dimensions toward shared identity and rhythm
      - label: Steward organizational narrative and brand coherence
      - label: Black Level, Zen Leadership Instructor designation
