---
mantra: "Don't Hoard. Share."
context:
  mission_rally_suffix_label: ": Living Structure"
  mission_statement_bridge:
    - "We move clarity into form — language, structure, and flow."
    - "We sense friction in the knowledge field and adjust with care."
    - "We welcome influence through open, visible practice."
  project_motivations_label: Project Motivations
  project_motivations:
    - "Our project is a shared practice of simplicity and coherence."
    - "We refine our systems, language, and flow through steady, mindful iteration."
    - "Each contribution strengthens the pattern of fearlessness in form."
  contribution_motivations_label: Contribution Motivations
  contribution_motivations:
    - "Make contribution as natural as conversation."
    - "Create infrastructure that teaches as it grows."
    - "Invite courage through transparency and simplicity."
  contribution_invitations_label: Contribution Invitations
  contribution_invitations:
    - "You sense where the system isn’t flowing."
    - "You refactor a phrase or function toward clarity."
    - "You offer a pattern that helps others move with ease."
  pullquote: "Ideation is fun, pull requests invite influence."
  designations_label: Leadership Designations
  designations_intention_label: Intention
  designations_aspects_label: Aspects
  leadership_flow:
    label: "⛩️ Leadership in Flow"
    limit: 16
  calls_to_action:
    - label: Inspect the Roots
      ref: repo
designations:
  - label: (Domain-Specific) Cultivator
    intention: Strengthen, simplify and broadcast the mission
    aspects:
      - label: Join Cultivator Circle regularly
      - label: Contribute to expertise in a mutually beneficial way
      - label: Green Level+, vouched for by existing Cultivator(s)
  - label: Project Cultivator
    intention: Integrate program, community, and platform work
    aspects:
      - label: Lead Cultivator Circle sessions periodically
      - label: Servant leader for (Domain-Specific) Cultivators
      - label: Black Level, vouched for by existing Cultivator(s)
  - label: Organizational Cultivator
    intention: Embody integrative leadership across social, technical, and brand ecosystems
    aspects:
      - label: Lead Cultivator Circle sessions regularly
      - label: Cultivate organizational culture and brand coherence
      - label: Black Level, Zen Leadership Instructor designation
---
