---
mantra: "Don’t Control. Co-Create."
mantra_mark: "Co-Create."
description: "An open-source dojo—where presence meets practice through shared stewardship. We refine structure as we train, evolving the system through care, contribution, and rhythm."
sections:
  - type: text
    data:
      label: "Dojo Infrastructure: Open Source’d"
      items:
        - "The Project is the living infrastructure of Mindset Dojo."
        - "It grows through contributions from those actively training."
        - "Open on GitHub—transparency and reciprocity guide its form."
  - type: text
    data:
      label: "Ways to Contribute"
      items:
        - "Refactor language, structure, or function toward clarity."
        - "Offer patterns or feedback that help others move with ease."
        - "Model reciprocity through guidance, review, and mentorship."
  - type: quote
    data:
      text: "Ideation is fun; pull requests invite influence."
  - type: list
    data:
      label: "Project Principles"
      items:
        - id: transparency
          label: "Transparency invites trust"
          description: "Openness in process, intent, and communication turns structure into a shared mirror — clarity replaces control."
        - id: contribution
          label: "Contribution shapes coherence"
          description: "Each act of authorship refines the system; when many hands move with care, complexity becomes rhythm."
        - id: stewardship
          label: "Stewardship evolves structure"
          description: "We tend the form as a living garden — pruning, nurturing, and redesigning as awareness matures."
  - type: designations
    data:
      label: "Leadership Designations"
      intention_label: "Intention"
      aspects_label: "Aspects"
      items:
        - label: "(Domain-Focused) Cultivator"
          intention: "Strengthen, clarify, and amplify the mission"
          aspects:
            - label: "Join Cultivator Circle regularly"
            - label: "Contribute to expertise in a mutually beneficial way"
            - label: "Green Level+, vouched for by existing Cultivator(s)"
        - label: "(Organizationally-Focused) Cultivator"
          intention: "Guide, harmonize, and model training authorship"
          aspects:
            - label: "Lead Cultivator Circle sessions regularly"
            - label: "Cultivate project culture and brand coherence"
            - label: "Black Level, vouched for by existing Cultivator(s)"
  - type: authors
    data:
      leadership_flow:
        label: "⛩️💫 Cultivator Circle"
        designation_type: project
        limit: 8
  - type: ctas
    data:
      items:
        - label: "Tend the Source"
          ref: repo
---
