# Top-level defaults for all file types
---
trailingComma: es5
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
bracketSpacing: true
bracketSameLine: false
arrowParens: always
embeddedLanguageFormatting: auto
endOfLine: lf
printWidth: 80
proseWrap: preserve
quoteProps: as-needed
htmlWhitespaceSensitivity: css
---

# YAML-specific overrides
---
overrides:
  - files: ["*.yml", "*.yaml"]
    options:
      parser: yaml
      tabWidth: 2
      singleQuote: false
      printWidth: 120
      trailingComma: none
      proseWrap: preserve
---

# Markdown files (including front-matter)
---
overrides:
  - files: ["*.md"]
    options:
      parser: markdown
      proseWrap: preserve
      printWidth: 100
      singleQuote: false
---

# HTML (layouts and includes with Liquid)
---
overrides:
  - files: ["_layouts/**/*.html", "_includes/**/*.html", "*.html"]
    options:
      parser: html
      htmlWhitespaceSensitivity: css
      printWidth: 100
      singleQuote: false
---

# CSS & SCSS
---
overrides:
  - files: ["*.css", "*.scss"]
    options:
      parser: css
      tabWidth: 2
      singleQuote: false
      trailingComma: none
      printWidth: 100
---

# JavaScript (also site scripts)
---
overrides:
  - files: ["*.js"]
    options:
      parser: babel
      tabWidth: 2
      trailingComma: es5
      semi: true
      singleQuote: false
      printWidth: 80
---
