# Sane default formatting for Prettier in Mindset Dojo

# Shared config matching Prettier's recommended defaults:
trailingComma: es5        # trailing commas in ES5 context (e.g., objects, arrays) :contentReference[oaicite:4]{index=4}
tabWidth: 2               # 2 spaces per indent level :contentReference[oaicite:5]{index=5}
useTabs: false            # use spaces, not tabs :contentReference[oaicite:6]{index=6}
semi: true                # use semicolons where applicable :contentReference[oaicite:7]{index=7}
singleQuote: false        # use double-quotes for strings :contentReference[oaicite:8]{index=8}
bracketSpacing: true      # include spaces between object brackets :contentReference[oaicite:9]{index=9}
bracketSameLine: false    # put closing bracket on new line :contentReference[oaicite:10]{index=10}
arrowParens: always       # always include parentheses in arrow functions :contentReference[oaicite:11]{index=11}
embeddedLanguageFormatting: auto  # format code inside markdown/YAML :contentReference[oaicite:12]{index=12}
endOfLine: lf             # use Unix-style line endings :contentReference[oaicite:13]{index=13}
htmlWhitespaceSensitivity: css  # handle whitespace based on CSS rules :contentReference[oaicite:14]{index=14}
printWidth: 80            # wrap lines at 80 chars for readability :contentReference[oaicite:15]{index=15}
proseWrap: preserve       # don’t re-wrap prose in markdown or YAML front matter :contentReference[oaicite:16]{index=16}
quoteProps: as-needed     # only quote object keys when necessary :contentReference[oaicite:17]{index=17}

# Specific overrides for YAML files:
overrides:
  - files: ["*.yaml", "*.yml"]
    options:
      tabWidth: 2
      singleQuote: false
      proseWrap: preserve
      printWidth: 120      # allow longer lines for long URLs/meta in Jekyll :contentReference[oaicite:18]{index=18}
      trailingComma: none  # avoid trailing commas in YAML (not supported) :contentReference[oaicite:19]{index=19}
