rules:
  no-todo: true
  no-dead-link: true
  max-length:
    max: 120
    severity: error
  sentence-length:
    max: 120
    severity: error
  list-item-spacing: true
  no-consecutive-blank-lines: true
  no-mixed-full-width-half-width-spaces: true
  period-in-list-item: true
