name: "Super-Linter Check"

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  super-linter:
    name: "Run Super-Linter"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          LOG_LEVEL: DEBUG
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
          SAVE_SUPER_LINTER_SUMMARY: true
          SAVE_SUPER_LINTER_OUTPUT: true
          SUPER_LINTER_OUTPUT_DIRECTORY_NAME: super-linter-report
          VALIDATE_ALL_CODEBASE: false    # only lint changed files in this PR
          AUTO_FIX: false                 # disable all auto-fix behavior
