name: "Super-Linter Check"

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  super-linter:
    name: "Run Super-Linter"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Import Super-Linter Environment Variables
        # Append all lines from .github/super-linter.env into the GitHub Actions environment
        run: |
          # Replace placeholder for GITHUB_TOKEN, then export all variables
          sed "s|__GITHUB_TOKEN__|${{ secrets.GITHUB_TOKEN }}|g" .github/super-linter.env >> "$GITHUB_ENV"

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.4.0
        # No additional env: block is needed because all variables are now in $GITHUB_ENV
